import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'

import { Toaster } from '@/components/ui/sonner'
import './globals.css'

export const metadata: Metadata = {
  title: 'JobMatch - Your Next Career Starts Here',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body className={`max-w-[90rem] mx-auto p-5 antialiased`}>
        {children}
        <Toaster richColors theme="light" />
      </body>
    </html>
  )
}
